### ISSUE TITLE
Docker Network Setup

### ISSUE THREAD

**Issue by prateekazam** [cloudmesh/cloudmesh-openapi#15]
- [ ] 1 - flask server should start on ip 0.0.0.0 , not on 127.0.0.1. If we are starting on 127.0.0.1 then it is not accessible from outside. (Prateek)
- [x] 2 - Commit initial version of docker file and sh file(Prateek)
- [x] 3 - Removed extra run command from docker file(Prateek)

**Comment by laszewsk** [comment]
This is rejected

flask should start on 127.0.0.1 as the 0.0.0.0 would open to all of the internet and be a potential security risk during development. 

if you need to use docker you need to do it in such a way that the ports are not exposed.

**Comment by laszewsk** [comment]
docker run -i --expose=5000 ...
docker run -d -p 5000:5000 ...

**Comment by prateekazam** [comment]
docker run -it -p 8080:8080 openapi3 , i am using this command. Since in container flask server is running on the localhost. I cannot able to access it from outside. Port routing is working fine. But when I start flask sever to 0.0.0.0 , i am able to access.

**Comment by prateekazam** [comment]
I have read from  https://docs.docker.com/network/host/ , and they have suggested running docker like docker run -it --network="host" -p 8080:8080 openapi3  bash
The above command is working,  Is this fine? But in this case, the container did not get any IP address.
