### ISSUE TITLE
cms openapi generator needs to support array type

### ISSUE THREAD

**Issue by jebeckford** [cloudmesh/cloudmesh-openapi#33]
Add to parser dict below
      
  parser = {
            'int': 'type: integer',
            'bool': 'type: boolean',
            'float': 'type: number',
            'str': 'type: string',
            'list': 'type: array\n          items: {}',
            'dict': 'type: object\n         additionalProperties: true'
        }

**Comment by bkegerreis** [comment]
should be safe enough to duplicate the structure for a list

**Comment by prateekazam** [comment]
Yes it is correct, but we have format issue as well. YAML syntax is invalid.

**Comment by prateekazam** [comment]
And we need to debug why the array input type is not working for restapi.

**Comment by bkegerreis** [comment]
just added type to parse_type() in generator.py, we should be able to try again now

**Comment by laszewsk** [comment]
please decide if mereg is possible i am out of time ....

**Comment by jebeckford** [comment]
Array support was added and the type for all arrays was defaulted to number.  There appears to be bug in Connexion preventing the use of valid OpenApi 3.0 syntax for either arrays with no data type or for arrays with multiple data types using oneOf tag.  So for now defaulting to number.
