### ISSUE TITLE
cms openapi generator should support no return from functions

### ISSUE THREAD

**Issue by jebeckford** [cloudmesh/cloudmesh-openapi#34]
The below section of code handles the response and it assumes that we always will find a return in the annotation.  Some functions won't have a return so need to make this optional.           

 responses = self.generate_response('200',
                                               v.__annotations__['return'],
                                               'OK')

**Comment by bkegerreis** [comment]
Can we just return 0?

**Comment by jebeckford** [comment]
we can probably leave out the entire responses section right?

**Comment by bkegerreis** [comment]
that might not be a valid openapi spec

**Comment by jebeckford** [comment]
From Swagger:

Empty Response Body
Some responses, such as 204 No Content, have no body. To indicate the response body is empty, do not specify a schema for the response. Swagger treats no schema as a response without a body.
      responses:
        204:
          description: The resource was deleted successfully.

**Comment by bkegerreis** [comment]
I think I'd rather just return zero so we at least know the function ran

**Comment by jebeckford** [comment]
Fixed by returning 204 in the openapi yaml for functions that have no return
