### ISSUE TITLE
server stop, list, ps errors

### ISSUE THREAD

**Issue by bkegerreis** [cloudmesh/cloudmesh-openapi#51]
`cms openapi server ps` and `cms openapi server stop NAME` have `TypeError: string indices must be integers` at line 175 of server.py. Apparently pinfo can come through as a string, not a dict as expected.

`cms openapi server list` and `cms openapi server list NAME` have `TypeError: list() got multiple values for argument 'name'` at line 300 of openapi.py

**Comment by andrewgoldfarb** [comment]
@bkegerreis you need to update your cloudmesh-common bundle. I was having the same error for the first half of this bug. Doing that should resolve the issue

**Comment by bkegerreis** [comment]
ah a failure message from cloudmesh-common was hiding deep within stderr when I tried to install. Looks like it has merge conflict markers hiding out in setup.py...
