### ISSUE TITLE
server.py requires host parameter to be provided

### ISSUE THREAD

**Issue by jebeckford** [cloudmesh/cloudmesh-openapi#52]
Per docstring all optional arguments should not be required:

openapi server start YAML [NAME]
                              [--directory=DIRECTORY]
                              [--port=PORT]
                              [--server=SERVER]
                              [--host=HOST]
                              [--verbose]
                              [--debug]
                              [--fg]
                              [--os]

**Comment by andrewgoldfarb** [comment]
There are none required, I can run the command with just the YAML path

What are you seeing?

**Comment by jebeckford** [comment]
Apparently it's a Windows thing only.  I resolved by setting defaults in the code.  Not sure why Mac/Ubuntu users were seeing it.
