### ISSUE TITLE
generator: --baseurl --directory

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-openapi#6]
I added a flag

--baseurl=DIRECTORY 

so we can place the function into a subdirectory so the operantionids do not have to be flat.

...  function.py --baseurl=DIRECTORY --directory=~

would create 

~/DIRECTORY/function.py 
~/function.yaml

**Comment by imishra1** [comment]
This is my updated code. Had to update the self.path in order to fix the issue.
      

 #self.path = path_expand(spec)
        self.path = directory+"/"+spec
        self.spec = self.path
        #self.spec = spec
        self.directory = os.path.dirname(self.path)
        self.host = host
        self.port = port
        self.debug = debug
        self.code = spec.replace("yaml","py")
        self.server = server
        self.server_command = ""

**Comment by jebeckford** [comment]
this was fixed a while back and since then we have a few different ways of deducing baseurl so closing issue.
